### ISSUE TITLE
Change link from "See all shell options"

### ISSUE THREAD

**Issue by jamiebianchini** [ludela/ludela.com#101]
Hey guys, we have excellent images of our shell collection Jake did.  Let's show the potential customers the colors and textures vs. sending them over to the tech page on this link.  

![image](https://cloud.githubusercontent.com/assets/20848499/19237689/1286ddaa-8eb3-11e6-8dd8-ae76abb8b3ac.png)

**Comment by jamiebianchini** [comment]
We have a great shell lineup here: https://www.dropbox.com/s/0lx4sgnp57eglv6/Candle%20full%20line%20of%20shells.jpg?dl=0

please stop linking out to broken tech page when they explore shells.

**Comment by tmesser** [comment]
The users can now see each shell as they select them on the store page, so this is handled now I believe.
