### ISSUE TITLE
Inconsistent footer

### ISSUE THREAD

**Issue by zeekay** [ludela/ludela.com#30]
Footer on index is different than slide-in footer on other pages. Same footer should be used throughout for consistency. Footers on subpages do not properly cover full height. Examples:

![http://vrz.io/hVqN/download/Image%202016-09-19%20at%2012.43.28%20PM.png](http://vrz.io/hVqN/download/Image%202016-09-19%20at%2012.43.28%20PM.png)
![http://vrz.io/hVuY/Image%202016-09-19%20at%2012.44.04%20PM.png](http://vrz.io/hVuY/Image%202016-09-19%20at%2012.44.04%20PM.png)

**Comment by baroper** [comment]
This is an issue for Mark Anderson

**Comment by MarkTA** [comment]
The footer hight has been fixed. You can check the updates on the staging site https://ludela-staging.herokuapp.com/about. I have added the general footer to the homepage to be implemented by @petealbertson

**Comment by tmesser** [comment]
This was sorted out during the store redesign.
