### ISSUE TITLE
Home page responsive layout issues

### ISSUE THREAD

**Issue by zeekay** [ludela/ludela.com#31]
Various issues were found at different layout sizes.

## All slides
- Missing navigation dots < 980px width

## Slide 1
![http://vrz.io/hVp8/Image%202016-09-19%20at%2012.36.58%20PM.png](http://vrz.io/hVp8/Image%202016-09-19%20at%2012.36.58%20PM.png)
![http://vrz.io/hVt2/Image%202016-09-19%20at%2012.36.36%20PM.png](http://vrz.io/hVt2/Image%202016-09-19%20at%2012.36.36%20PM.png)
![http://vrz.io/hVn8/Image%202016-09-19%20at%2012.36.32%20PM.png](http://vrz.io/hVn8/Image%202016-09-19%20at%2012.36.32%20PM.png)

## Slide 3
- Not centered correctly accounting for side dots
- Very difficult to scroll through slowly and read features with < 800px width. Does not have the same scroll delay that the rest of the site does so user zooms past them.
- Would look better with two column layout between 800px and 667px.

![http://vrz.io/hVlj/Image%202016-09-19%20at%2012.45.36%20PM.png](http://vrz.io/hVlj/Image%202016-09-19%20at%2012.45.36%20PM.png)
![http://vrz.io/hVjs/Image%202016-09-19%20at%2012.51.41%20PM.png](http://vrz.io/hVjs/Image%202016-09-19%20at%2012.51.41%20PM.png)

## Slide 4
Exhibits similar issues as Slide 3. Note: particularly broken in landscape:
- ![http://vrz.io/hVuu/Image%202016-09-19%20at%2012.54.33%20PM.png](http://vrz.io/hVuu/Image%202016-09-19%20at%2012.54.33%20PM.png)

## Slide 5
Same issues as 3, 4.

## Slide 6
Possible to completely obscure message about ivory being only color available: ![http://vrz.io/hVsA/Image%202016-09-19%20at%2012.55.33%20PM.png](http://vrz.io/hVsA/Image%202016-09-19%20at%2012.55.33%20PM.png)

Exploded view can be broken in odd ways:
![http://vrz.io/hVti/Image%202016-09-19%20at%2012.58.13%20PM.png](http://vrz.io/hVti/Image%202016-09-19%20at%2012.58.13%20PM.png)
![http://vrz.io/hVwW/Image%202016-09-19%20at%2012.58.04%20PM.png](http://vrz.io/hVwW/Image%202016-09-19%20at%2012.58.04%20PM.png)

## Slide 7
- Impossible to scroll to at certain resolutions.
- Layout is very wonky at smaller resolutions.

**Comment by baroper** [comment]
Just noting that we only have 1 breakpoint, so only desktop and mobile designs. There are not nav dots on mobile according to approved designs. @petealbertson - Can you handle this ticket? Do not worry about adding nav dots on mobile.

**Comment by zeekay** [comment]
We need nav dots added back for mobile. I don't know who approved that but it makes it really unclear where you are in the page w/o. Unless we switch to full scrolling.

**Comment by MarkTA** [comment]
I'll take care of this.

**Comment by baroper** [comment]
Jamie approved. However, we can add them, just a smaller fish to fry behind these other issues. Let's add that as a separate issue so we can just handle these other items here. @zeekay

**Comment by MarkTA** [comment]
It's only 1 line of code, it's done
