### ISSUE TITLE
Menu behavior < 800px

### ISSUE THREAD

**Issue by zeekay** [ludela/ludela.com#32]
Menu, which pushes content right > 800px width, still pushes content < 800px width despite it being a full-width drop-down. Should also fully drop down, which it doesn't. Example: ![http://vrz.io/hW8B/Image%202016-09-19%20at%204.14.49%20PM.png](http://vrz.io/hW8B/Image%202016-09-19%20at%204.14.49%20PM.png)

**Comment by baroper** [comment]
@petealbertson - This is for you to do.
