### ISSUE TITLE
Icons to swap on "Piece of mind" slide

### ISSUE THREAD

**Issue by baroper** [ludela/ludela.com#33]
Safe Wax Design needs the following icon: 
<img width="118" alt="cursor_and_icon_set_v_6_outlined_pdf__1_page_" src="https://cloud.githubusercontent.com/assets/20731951/18651202/c2a0f710-7e7e-11e6-901a-9331d6ba30da.png">

Safe Burn Design:
<img width="115" alt="icon_set_v_6_outlined_pdf__1_page_" src="https://cloud.githubusercontent.com/assets/20731951/18651265/0dfd51cc-7e7f-11e6-8101-e3a989bec207.png">

Find icons here: https://www.dropbox.com/sh/5plqe69imaw3otz/AADtsptDCIyqweewB_kTt1Tta?dl=0

@petealbertson

**Comment by baroper** [comment]
Including fixing this icon that is too small:
![cursor_and_ludela](https://cloud.githubusercontent.com/assets/20731951/18686861/6128a708-7f32-11e6-9903-5862c950def8.png)

@petealbertson

**Comment by tmesser** [comment]
This was handled during the store redesign.
