### ISSUE TITLE
On About, the design is stretched too tall for the window, even on large displays

### ISSUE THREAD

**Issue by baroper** [ludela/ludela.com#37]
Issue is that when the page is scrolled down to the new slide in the timeline on desktop the text is pushed up really high on the window. Tons of whitespace. ![cursor_and_ludela](https://cloud.githubusercontent.com/assets/20731951/18651684/aaba8f46-7e81-11e6-9a2e-436d72df0947.png)

@MarkTA

This is for Anderson

**Comment by MarkTA** [comment]
@baroper please refresh heroku and check the issue again
