### ISSUE TITLE
Change or Remove Floating Call to Action

### ISSUE THREAD

**Issue by jamiebianchini** [ludela/ludela.com#39]
Now that we are not in "pre-launch" we should change this floating call to action..

from current: EARLY BIRDS RECIEVE 20% OFF + FREE CANDLE REFILLS

Change to: Join LuDela for Warm Updates and Dazzling Deals

And if you feel it's best to remove this floating bar i'll let you guys lead.

**Comment by tmesser** [comment]
This was handled by the store redesign.
