### ISSUE TITLE
Shopping Cart and Checkout Content from Jamie

### ISSUE THREAD

**Issue by jamiebianchini** [ludela/ludela.com#40]
hey guys, i'm getting in the car now to bay area.  will be in mountains a few hours from tahoe down.

so the reference doc is updated after many talks.  $99 offer, $199 retail + one-month trial subscription.

data is:

1) in reference doc
2) checkout / cart content is here: https://www.dropbox.com/s/lujfauvf3a1zjce/LuDela%20Pricing%20and%20Checkout%20Content%20.docx?dl=0

this should keep ya busy on top of all the other adventures your in!

Go get em!  excited to see this baby done! :)

**Comment by tmesser** [comment]
This was superceded by the store redesign and has been completed.
