### ISSUE TITLE
Final changes to site before ads go live

### ISSUE THREAD

**Issue by jamiebianchini** [ludela/ludela.com#48]
Hey guys, here's what i'm thinking and hoping it's not too difficult.

1) Change floating video text  from"see the LuDela" to "Play Video"
2) Last page Modification--this is our closer page...should be powerful and call to action..

- Change brush font "Join Us" to "Get Yours Now"
- Change text above newsletter to "Signup for Warm Updates and Dazzling Deals"

3) Ideally we'd have logos of press coverage on this last page.  so far we have: 

CNET, Gizmodo,Chip Chick, Digital Trends, Product Hunt, Tech Crunch, Popular Mechanics, Apartment Therapy, Yahoo Tech.

anyone around to bang these out before we turn on ads??

**Comment by tmesser** [comment]
These are sorted out except for I think the press coverage, which is already in another issue.
