### ISSUE TITLE
Footer on homepage is screwy on mobile

### ISSUE THREAD

**Issue by zeekay** [ludela/ludela.com#50]
![https://d3vv6lp55qjaqc.cloudfront.net/items/1Z330c1M2i423m3F0P0L/Image%202016-09-20%20at%208.49.26%20PM.png?X-CloudApp-Visitor-Id=1755694&v=d8a7b350](https://d3vv6lp55qjaqc.cloudfront.net/items/1Z330c1M2i423m3F0P0L/Image%202016-09-20%20at%208.49.26%20PM.png?X-CloudApp-Visitor-Id=1755694&v=d8a7b350)

**Comment by baroper** [comment]
@zeekay - @petealbertson fixed this yesterday afternoon
