### ISSUE TITLE
checkout issue reported

### ISSUE THREAD

**Issue by jamiebianchini** [ludela/ludela.com#52]
Andy & I both were trying to order a LuDela this morning and discovered that the scrolling when we got to the "purchasing info" portion didn't work.  I couldn't really diagnose root cause of the problem, but it seemed like maybe when the cursor was inside one of the cells (Select Your State), etc the overall window wouldn't scroll.  I'm not sure if that was the "user error" or not, but I think it might be.  I had selected my state already, so it wasn't actually scrolling anything visually within that cell.

I wasn't entirely certain what I did that finally allowed things to work differently, but I know I moved from the trackpad (Mac) to the "down arrow".

**Comment by zeekay** [comment]
This is fixed already.
