### ISSUE TITLE
smaller lower banner from mobile site?

### ISSUE THREAD

**Issue by jamiebianchini** [ludela/ludela.com#53]
it's taking up a huge 3x chunk of real estate.  let's make it one line or remove it.

**Comment by baroper** [comment]
@zeekay - What do you suggest to do here?

**Comment by baroper** [comment]
@zeekay - Jamie is suggesting removing or reducing. What do we want to do?

**Comment by zeekay** [comment]
Just remove from < ios 6+ height.
—
Zach Kelling
$ curl monoid.io/say-hi | python
zk@monoid.io / (913) 777-9708

**Comment by davidtai** [comment]
applies to old site.
