### ISSUE TITLE
Check Box for Gift in Checkout Process + Wording

### ISSUE THREAD

**Issue by jamiebianchini** [ludela/ludela.com#55]
hey guys when folks buy they get a 1-month free trial subscription and they need that wording.  Plus they need a check box for gift and option to get a gift greeting card + fill in some text.

we have 3+ holiday gift guides covering us and we have to let folks choose to get a card the publication promised during checkout.  

https://www.dropbox.com/s/lujfauvf3a1zjce/LuDela%20Pricing%20and%20Checkout%20Content%20.docx?dl=0 is the link

the link in the checkout site to "gift card" should be a java popup to: https://www.dropbox.com/s/7e1ye74smgiiwbu/Holiday%20Gift%20Guide%20-%20LuDela.png?dl=0

**Comment by tmesser** [comment]
This was subsumed in the store update.
