### ISSUE TITLE
Add founder photo in about us, https://ludela.com/about#Our-Story-8

### ISSUE THREAD

**Issue by jamiebianchini** [ludela/ludela.com#66]
now we have a placeholder logo of Surface Ink in the 2nd to last photo--https://ludela.com/about#Our-Story-8

please use the photo of Eric and I from this link: https://www.dropbox.com/s/wp77a2445f4sus6/IMG_1315.JPG?dl=0

**Comment by baroper** [comment]
@MarkTA This one's for you.

**Comment by tmesser** [comment]
This got done during the store update.

**Comment by jamiebianchini** [comment]
No, it's not done.  at the bottom of "about" still looks like this and should have that photo of the founders in there:

![image](https://cloud.githubusercontent.com/assets/20848499/19493311/fe8fe2ec-952e-11e6-8b66-c54750357257.png)

**Comment by davidtai** [comment]
Which photo of the founders is it?  I believe that Helpful Human was asking about this too.

**Comment by jamiebianchini** [comment]
this is the photo https://www.dropbox.com/s/wp77a2445f4sus6/IMG_1315.JPG?dl=0

**Comment by jamiebianchini** [comment]
We want to close this project, @dtai.  this is a quick one but important as we build our list and get ready for re-launch
