### ISSUE TITLE
Fix of Team

### ISSUE THREAD

**Issue by jamiebianchini** [ludela/ludela.com#69]
Hi everyone,

Team needs to be our entire team, not just our advisors.  now we show just our 5 advisors on our team.  We have a full team and our photos and titles are here: Team sections should be:

To truly revolutionize the way the world interacts with natural light and realize our vision to bring Better Light and Better Lives we attracted a world-class team of talent. Our team is dispersed between two core locations in San Jose, California (engineering & product design with our partner Surface Ink) and in the Eastern Sierra Nevada town of Minden, Nevada.

Insert our team with photos: 

https://www.dropbox.com/sh/42fxvcpxwdxmzj8/AACROA1jY5pQRky7KqPCuC6Pa?dl=0https://www.dropbox.com/sh/42fxvcpxwdxmzj8/AACROA1jY5pQRky7KqPCuC6Pa?dl=0 

Then "Our Advisors"

leave the 5 boxes of the 5 advisors there.

hope that's helpful.  thanks!

**Comment by baroper** [comment]
@MarkTA This is you.

**Comment by tmesser** [comment]
Been done for a while, just hasn't been closed.
