### ISSUE TITLE
Press Page

### ISSUE THREAD

**Issue by zeekay** [ludela/ludela.com#70]
Need press page with contact details, press releases, videos, images, logo and articles under coverage. LuDela has 45 articles and counting.

**Comment by tmesser** [comment]
This should be an entirely new page, with all the content linked to the press they've been having.  This should be plugged into Contentful so others can edit it as new articles launch.

**Comment by jamiebianchini** [comment]
I thought HH was designing this.  last i had heard from @zeekay .

**Comment by tmesser** [comment]
David completed this and integrated it into Contentful on 10/28.  I added a data model to Contentful and added 5 examples of fully fleshed out press articles.
