### ISSUE TITLE
Dead Signup Bar??  No Login?

### ISSUE THREAD

**Issue by jamiebianchini** [ludela/ludela.com#74]
when i go to www.LuDela.com only see a CTA and no login.  

looks like this.  am i logged in already?  is that why?  

![dead-footer](https://cloud.githubusercontent.com/assets/20848499/18758206/f8448b5a-80ab-11e6-9dca-b522896af5b0.jpg)

**Comment by petealbertson** [comment]
As a non-logged in user I see the signup/login links.

![image](https://cloud.githubusercontent.com/assets/5597250/18758900/d0f18334-80ae-11e6-991e-22d540416507.png)

**Comment by davidtai** [comment]
fixed
