### ISSUE TITLE
IMPORTANT: Change Checkout Cart "Special Offer" text

### ISSUE THREAD

**Issue by jamiebianchini** [ludela/ludela.com#90]
FYI, you misspelled LuDela.  Not two LL's in ;)  

Please also change the text to something totally exploratory, zero risk:

SPECIAL OFFER
Yes! I would like a free month of LuDela refills and more information about saving time and money with LuDela's subscription plans.  No strings attached!

**Comment by zeekay** [comment]
Fixed typo, new language is not an improvement. What are they checking box for? So you can give them free stuff and send them more info? I thought the point was to get people to subscribe, no?

**Comment by jamiebianchini** [comment]
My thought is to remove friction.  Nobody knows us now and bringing up $9.99 auto billing this early in relationship seems a bit much.  either way they will need refills if they love us, and they will, so let's just give them the firs step and we can followup and share the scented and unscented plans as they come out, and maximize conversions.  this was my thought.  let's try this and see if we get any better conversions.  we have time to get folks on subscriptions and show them the value of that.
