### ISSUE TITLE
Please implment Discount Pricing per reference table

### ISSUE THREAD

**Issue by jamiebianchini** [ludela/ludela.com#94]
**I have updated the discount profile.  it's modest savings but want to update this and put "Bundle LuDelas to Save even More**" on top of cart.  so the savings is just 

189 for 2 
279 for 3 

rest of the pricing table is at $93/LuDela.  

don't want to go too low as we'll likely have coupons floating around as well...

thanks for doing this.  i have a few people who emailed asking about this cuz i mention in the FAQ.

**Comment by davidtai** [comment]
This is done in the store
