### ISSUE TITLE
Change "hi@ludela.com" to "hello@ludela.com" for all transactional email

### ISSUE THREAD

**Issue by jamiebianchini** [ludela/ludela.com#97]
right now auto emails are being sent to customers from hi@ludela.com.  we don't have that email address.  it should be hello@ludela.com.  can you change ASAP?  thanks!  had a complaint that led to a cancellation.  

Jamie

**Comment by zeekay** [comment]
We can change this but you should just add hi@ludela.com as an alias to prevent any future problems.

**Comment by jamiebianchini** [comment]
got it.  we can close this now...leave as is 👍
